---
title: "Confusion Matrix and ROC"
author: "Archana Gadicharla"
date: "2024-02-25"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#loading the packages.

```{r}
library(ISLR)
library(caret)
library(class)
```
#viewing the data and drawing the summary of it.
```{r}
#View(Default)
summary(Default)
```
#Normalizing the data.
```{r}
norm_model <- preProcess(Default,method = c('range'))
Default_normalized <- predict(norm_model,Default)
summary(Default_normalized)
head(Default_normalized)
```
#Setting up a knn classification model.
```{r}
set.seed(123)
model <- train(default~balance+income,data=Default_normalized,method="knn")
model

set.seed(123)
Serach_grid <- expand.grid(k=c(2,7,9,15))
model <- train(default~balance+income,data=Default_normalized,method='knn',
               tuneGrid=Serach_grid)
model

set.seed(123)
Serach_grid <- expand.grid(k=c(2:20))
model <- train(default~balance+income,data=Default_normalized,method="knn",
               tuneGrid=Serach_grid)
print(model)
```
```{r}
Default_normalized <- Default_normalized[,-2]
Index_Train <-createDataPartition(Default_normalized$default,p=0.8,list = FALSE)
#creating a training data set
Train <- Default_normalized[Index_Train,]
#creating a testing set
Test <- Default_normalized[-Index_Train,]
head(Train)
head(Test)
```

```{r}
#using predictor variables for knn classification
Train_Predictors <- Train[,2:3]
Test_Predictors <- Test[,2:3]

Train_labels <- Train[,1]
Test_labels <- Test[,1]

Predicted_Test_labels <- knn(Train_Predictors,Test_Predictors,cl=Train_labels,k=4)
head(Predicted_Test_labels)
```
```{r}
#loading gmodels package
chooseCRANmirror(ind=1)
library("gmodels")
```

```{r}
CrossTable(x=Test_labels,y=Predicted_Test_labels,prop.chisq = FALSE)
```


```{r}
Predicted_Test_labels<-knn(Train_Predictors,Test_Predictors,cl=Train_labels,k=100,prob = TRUE)
class_prob <- attr(Predicted_Test_labels,"prob")
head(class_prob)
```

#creating confusion matrix.
```{r}
example <- confusionMatrix(data=Predicted_Test_labels,reference=Test_labels)
example
```
#loading pROC package.
```{r}
library(pROC)
```

plotting ROC curve
```{r}
roc_curve <-roc(Test_labels,class_prob)
plot(roc_curve,main = "ROC Curve",col = "red")
```
```{r}
roc_curve <- roc(Predicted_Test_labels,class_prob)
roc1 <- plot.roc(Predicted_Test_labels,class_prob,main="Statistical comparison",
                 percent=TRUE,
                 col="orange")
roc2 <- lines.roc(Predicted_Test_labels,class_prob,percent=TRUE,
                  col="green")
testobj <- roc.test(roc1,roc2)
text(50,50,lables=paste("p-value=",format.pval(testobj$p.value)),adj=c(0,.2))
```
```{r}
plot.roc(Predicted_Test_labels,class_prob,main="Confidence interval of a threshold",percent=TRUE,
         ci=TRUE,of="thresholds",
         thresholds="best",
         print.thres="best")
```

